import type { Category, ProductWithCategory } from "@/lib/types";

export const demoCategories: Category[] = [
  { id: "cat-entradas", name: "Entradas", created_at: new Date().toISOString() },
  { id: "cat-principales", name: "Principales", created_at: new Date().toISOString() },
  { id: "cat-pastas", name: "Pastas", created_at: new Date().toISOString() },
  { id: "cat-postres", name: "Postres", created_at: new Date().toISOString() },
  { id: "cat-bebidas", name: "Bebidas", created_at: new Date().toISOString() },
];

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const demoProducts: ProductWithCategory[] = [
  {
    id: "prod-1",
    name: "Burrata con tomates asados",
    description: "Burrata cremosa, tomates confitados, pesto de albahaca y focaccia tostada.",
    price: 9200,
    image_url: img("photo-1551183053-bf91a1d81141"),
    category_id: "cat-entradas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-entradas", name: "Entradas" },
  },
  {
    id: "prod-2",
    name: "Croquetas de hongos",
    description: "Croquetas doradas con alioli de ajo negro y hojas frescas.",
    price: 7100,
    image_url: img("photo-1541014741259-de529411b96a"),
    category_id: "cat-entradas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-entradas", name: "Entradas" },
  },
  {
    id: "prod-3",
    name: "Tartar de salmón",
    description: "Salmón fresco, palta, pepino, lima y chips de arroz.",
    price: 10800,
    image_url: img("photo-1560717845-968823efbee1"),
    category_id: "cat-entradas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-entradas", name: "Entradas" },
  },
  {
    id: "prod-4",
    name: "Ojo de bife grillado",
    description: "Corte premium con papas rotas, chimichurri cítrico y vegetales al fuego.",
    price: 18500,
    image_url: img("photo-1558030006-450675393462"),
    category_id: "cat-principales",
    created_at: new Date().toISOString(),
    categories: { id: "cat-principales", name: "Principales" },
  },
  {
    id: "prod-5",
    name: "Pollo braseado al limón",
    description: "Pollo de campo, salsa de limón y hierbas con puré de calabaza.",
    price: 13200,
    image_url: img("photo-1598515214211-89d3c73ae83b"),
    category_id: "cat-principales",
    created_at: new Date().toISOString(),
    categories: { id: "cat-principales", name: "Principales" },
  },
  {
    id: "prod-6",
    name: "Pesca del día",
    description: "Filet grillado, crema de hinojo, ensalada tibia y aceite verde.",
    price: 16900,
    image_url: img("photo-1467003909585-2f8a72700288"),
    category_id: "cat-principales",
    created_at: new Date().toISOString(),
    categories: { id: "cat-principales", name: "Principales" },
  },
  {
    id: "prod-7",
    name: "Risotto de azafrán",
    description: "Arroz carnaroli, azafrán, parmesano estacionado y limón.",
    price: 12800,
    image_url: img("photo-1476124369491-e7addf5db371"),
    category_id: "cat-pastas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-pastas", name: "Pastas" },
  },
  {
    id: "prod-8",
    name: "Tagliatelle al ragú",
    description: "Pasta fresca con ragú de cocción lenta y queso pecorino.",
    price: 12100,
    image_url: img("photo-1551183053-bf91a1d81141"),
    category_id: "cat-pastas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-pastas", name: "Pastas" },
  },
  {
    id: "prod-9",
    name: "Ravioles de calabaza",
    description: "Ravioles caseros, manteca noisette, salvia y semillas tostadas.",
    price: 11600,
    image_url: img("photo-1587740908075-9e245070dfaa"),
    category_id: "cat-pastas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-pastas", name: "Pastas" },
  },
  {
    id: "prod-10",
    name: "Tiramisú de la casa",
    description: "Mascarpone, café espresso, cacao amargo y vainillas suaves.",
    price: 6200,
    image_url: img("photo-1571877227200-a0d98ea607e9"),
    category_id: "cat-postres",
    created_at: new Date().toISOString(),
    categories: { id: "cat-postres", name: "Postres" },
  },
  {
    id: "prod-11",
    name: "Flan quemado",
    description: "Flan casero con caramelo tostado y crema batida.",
    price: 5400,
    image_url: img("photo-1464305795204-6f5bbfc7fb81"),
    category_id: "cat-postres",
    created_at: new Date().toISOString(),
    categories: { id: "cat-postres", name: "Postres" },
  },
  {
    id: "prod-12",
    name: "Pavlova de estación",
    description: "Merengue crocante, crema ligera y frutas frescas.",
    price: 6900,
    image_url: img("photo-1488477181946-6428a0291777"),
    category_id: "cat-postres",
    created_at: new Date().toISOString(),
    categories: { id: "cat-postres", name: "Postres" },
  },
  {
    id: "prod-13",
    name: "Limonada de menta",
    description: "Limón exprimido, menta fresca, almíbar suave y soda.",
    price: 3900,
    image_url: img("photo-1621263764928-df1444c5e859"),
    category_id: "cat-bebidas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-bebidas", name: "Bebidas" },
  },
  {
    id: "prod-14",
    name: "Spritz de pomelo",
    description: "Aperitivo cítrico, pomelo rosado, burbujas y romero.",
    price: 6200,
    image_url: img("photo-1556679343-c7306c1976bc"),
    category_id: "cat-bebidas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-bebidas", name: "Bebidas" },
  },
  {
    id: "prod-15",
    name: "Café frío especiado",
    description: "Cold brew, cardamomo, naranja y espuma de leche.",
    price: 4300,
    image_url: img("photo-1461023058943-07fcbe16d735"),
    category_id: "cat-bebidas",
    created_at: new Date().toISOString(),
    categories: { id: "cat-bebidas", name: "Bebidas" },
  },
];
